// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: robot_call.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RobotCall {

  /// <summary>Holder for reflection information generated from robot_call.proto</summary>
  public static partial class RobotCallReflection {

    #region Descriptor
    /// <summary>File descriptor for robot_call.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RobotCallReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChByb2JvdF9jYWxsLnByb3RvEgpyb2JvdF9jYWxsIvkCCgxSb2JvdENhbGxp",
            "bmcSGwoTc2hvdWxkZXJfcGl0Y2hfbGVmdBgBIAEoAhIcChRzaG91bGRlcl9w",
            "aXRjaF9yaWdodBgCIAEoAhISCgpiaWNlcF9sZWZ0GAMgASgCEhMKC2JpY2Vw",
            "X3JpZ2h0GAQgASgCEhoKEnNob3VsZGVyX3JvbGxfbGVmdBgFIAEoAhIbChNz",
            "aG91bGRlcl9yb2xsX3JpZ2h0GAYgASgCEhkKEWZvcmVhcm1fcm9sbF9sZWZ0",
            "GAcgASgCEhoKEmZvcmVhcm1fcm9sbF9yaWdodBgIIAEoAhIaChJ3cmlzdF9m",
            "bGV4aW9uX2xlZnQYCSABKAISGwoTd3Jpc3RfZmxleGlvbl9yaWdodBgKIAEo",
            "AhIWCg53cmlzdF95YXdfbGVmdBgLIAEoAhIXCg93cmlzdF95YXdfcmlnaHQY",
            "DCABKAISFAoMZ3JpcHBlcl9sZWZ0GA0gASgCEhUKDWdyaXBwZXJfcmlnaHQY",
            "DiABKAIiMAoIUmVzcG9uc2USEwoLdHJhbnNtaXR0ZWQYASABKAgSDwoHbWVz",
            "c2FnZRgCIAEoCTJPCglSb2JvdENhbGwSQgoQU2VuZEluc3RydWN0aW9ucxIY",
            "LnJvYm90X2NhbGwuUm9ib3RDYWxsaW5nGhQucm9ib3RfY2FsbC5SZXNwb25z",
            "ZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RobotCall.RobotCalling), global::RobotCall.RobotCalling.Parser, new[]{ "ShoulderPitchLeft", "ShoulderPitchRight", "BicepLeft", "BicepRight", "ShoulderRollLeft", "ShoulderRollRight", "ForearmRollLeft", "ForearmRollRight", "WristFlexionLeft", "WristFlexionRight", "WristYawLeft", "WristYawRight", "GripperLeft", "GripperRight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RobotCall.Response), global::RobotCall.Response.Parser, new[]{ "Transmitted", "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RobotCalling : pb::IMessage<RobotCalling>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RobotCalling> _parser = new pb::MessageParser<RobotCalling>(() => new RobotCalling());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RobotCalling> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RobotCall.RobotCallReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotCalling() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotCalling(RobotCalling other) : this() {
      shoulderPitchLeft_ = other.shoulderPitchLeft_;
      shoulderPitchRight_ = other.shoulderPitchRight_;
      bicepLeft_ = other.bicepLeft_;
      bicepRight_ = other.bicepRight_;
      shoulderRollLeft_ = other.shoulderRollLeft_;
      shoulderRollRight_ = other.shoulderRollRight_;
      forearmRollLeft_ = other.forearmRollLeft_;
      forearmRollRight_ = other.forearmRollRight_;
      wristFlexionLeft_ = other.wristFlexionLeft_;
      wristFlexionRight_ = other.wristFlexionRight_;
      wristYawLeft_ = other.wristYawLeft_;
      wristYawRight_ = other.wristYawRight_;
      gripperLeft_ = other.gripperLeft_;
      gripperRight_ = other.gripperRight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotCalling Clone() {
      return new RobotCalling(this);
    }

    /// <summary>Field number for the "shoulder_pitch_left" field.</summary>
    public const int ShoulderPitchLeftFieldNumber = 1;
    private float shoulderPitchLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ShoulderPitchLeft {
      get { return shoulderPitchLeft_; }
      set {
        shoulderPitchLeft_ = value;
      }
    }

    /// <summary>Field number for the "shoulder_pitch_right" field.</summary>
    public const int ShoulderPitchRightFieldNumber = 2;
    private float shoulderPitchRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ShoulderPitchRight {
      get { return shoulderPitchRight_; }
      set {
        shoulderPitchRight_ = value;
      }
    }

    /// <summary>Field number for the "bicep_left" field.</summary>
    public const int BicepLeftFieldNumber = 3;
    private float bicepLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float BicepLeft {
      get { return bicepLeft_; }
      set {
        bicepLeft_ = value;
      }
    }

    /// <summary>Field number for the "bicep_right" field.</summary>
    public const int BicepRightFieldNumber = 4;
    private float bicepRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float BicepRight {
      get { return bicepRight_; }
      set {
        bicepRight_ = value;
      }
    }

    /// <summary>Field number for the "shoulder_roll_left" field.</summary>
    public const int ShoulderRollLeftFieldNumber = 5;
    private float shoulderRollLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ShoulderRollLeft {
      get { return shoulderRollLeft_; }
      set {
        shoulderRollLeft_ = value;
      }
    }

    /// <summary>Field number for the "shoulder_roll_right" field.</summary>
    public const int ShoulderRollRightFieldNumber = 6;
    private float shoulderRollRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ShoulderRollRight {
      get { return shoulderRollRight_; }
      set {
        shoulderRollRight_ = value;
      }
    }

    /// <summary>Field number for the "forearm_roll_left" field.</summary>
    public const int ForearmRollLeftFieldNumber = 7;
    private float forearmRollLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ForearmRollLeft {
      get { return forearmRollLeft_; }
      set {
        forearmRollLeft_ = value;
      }
    }

    /// <summary>Field number for the "forearm_roll_right" field.</summary>
    public const int ForearmRollRightFieldNumber = 8;
    private float forearmRollRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ForearmRollRight {
      get { return forearmRollRight_; }
      set {
        forearmRollRight_ = value;
      }
    }

    /// <summary>Field number for the "wrist_flexion_left" field.</summary>
    public const int WristFlexionLeftFieldNumber = 9;
    private float wristFlexionLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float WristFlexionLeft {
      get { return wristFlexionLeft_; }
      set {
        wristFlexionLeft_ = value;
      }
    }

    /// <summary>Field number for the "wrist_flexion_right" field.</summary>
    public const int WristFlexionRightFieldNumber = 10;
    private float wristFlexionRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float WristFlexionRight {
      get { return wristFlexionRight_; }
      set {
        wristFlexionRight_ = value;
      }
    }

    /// <summary>Field number for the "wrist_yaw_left" field.</summary>
    public const int WristYawLeftFieldNumber = 11;
    private float wristYawLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float WristYawLeft {
      get { return wristYawLeft_; }
      set {
        wristYawLeft_ = value;
      }
    }

    /// <summary>Field number for the "wrist_yaw_right" field.</summary>
    public const int WristYawRightFieldNumber = 12;
    private float wristYawRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float WristYawRight {
      get { return wristYawRight_; }
      set {
        wristYawRight_ = value;
      }
    }

    /// <summary>Field number for the "gripper_left" field.</summary>
    public const int GripperLeftFieldNumber = 13;
    private float gripperLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float GripperLeft {
      get { return gripperLeft_; }
      set {
        gripperLeft_ = value;
      }
    }

    /// <summary>Field number for the "gripper_right" field.</summary>
    public const int GripperRightFieldNumber = 14;
    private float gripperRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float GripperRight {
      get { return gripperRight_; }
      set {
        gripperRight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RobotCalling);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RobotCalling other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ShoulderPitchLeft, other.ShoulderPitchLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ShoulderPitchRight, other.ShoulderPitchRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(BicepLeft, other.BicepLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(BicepRight, other.BicepRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ShoulderRollLeft, other.ShoulderRollLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ShoulderRollRight, other.ShoulderRollRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ForearmRollLeft, other.ForearmRollLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ForearmRollRight, other.ForearmRollRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(WristFlexionLeft, other.WristFlexionLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(WristFlexionRight, other.WristFlexionRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(WristYawLeft, other.WristYawLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(WristYawRight, other.WristYawRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(GripperLeft, other.GripperLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(GripperRight, other.GripperRight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ShoulderPitchLeft != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ShoulderPitchLeft);
      if (ShoulderPitchRight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ShoulderPitchRight);
      if (BicepLeft != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(BicepLeft);
      if (BicepRight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(BicepRight);
      if (ShoulderRollLeft != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ShoulderRollLeft);
      if (ShoulderRollRight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ShoulderRollRight);
      if (ForearmRollLeft != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ForearmRollLeft);
      if (ForearmRollRight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ForearmRollRight);
      if (WristFlexionLeft != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(WristFlexionLeft);
      if (WristFlexionRight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(WristFlexionRight);
      if (WristYawLeft != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(WristYawLeft);
      if (WristYawRight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(WristYawRight);
      if (GripperLeft != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(GripperLeft);
      if (GripperRight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(GripperRight);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ShoulderPitchLeft != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(ShoulderPitchLeft);
      }
      if (ShoulderPitchRight != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(ShoulderPitchRight);
      }
      if (BicepLeft != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(BicepLeft);
      }
      if (BicepRight != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(BicepRight);
      }
      if (ShoulderRollLeft != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(ShoulderRollLeft);
      }
      if (ShoulderRollRight != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(ShoulderRollRight);
      }
      if (ForearmRollLeft != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(ForearmRollLeft);
      }
      if (ForearmRollRight != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(ForearmRollRight);
      }
      if (WristFlexionLeft != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(WristFlexionLeft);
      }
      if (WristFlexionRight != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(WristFlexionRight);
      }
      if (WristYawLeft != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(WristYawLeft);
      }
      if (WristYawRight != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(WristYawRight);
      }
      if (GripperLeft != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(GripperLeft);
      }
      if (GripperRight != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(GripperRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ShoulderPitchLeft != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(ShoulderPitchLeft);
      }
      if (ShoulderPitchRight != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(ShoulderPitchRight);
      }
      if (BicepLeft != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(BicepLeft);
      }
      if (BicepRight != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(BicepRight);
      }
      if (ShoulderRollLeft != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(ShoulderRollLeft);
      }
      if (ShoulderRollRight != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(ShoulderRollRight);
      }
      if (ForearmRollLeft != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(ForearmRollLeft);
      }
      if (ForearmRollRight != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(ForearmRollRight);
      }
      if (WristFlexionLeft != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(WristFlexionLeft);
      }
      if (WristFlexionRight != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(WristFlexionRight);
      }
      if (WristYawLeft != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(WristYawLeft);
      }
      if (WristYawRight != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(WristYawRight);
      }
      if (GripperLeft != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(GripperLeft);
      }
      if (GripperRight != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(GripperRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ShoulderPitchLeft != 0F) {
        size += 1 + 4;
      }
      if (ShoulderPitchRight != 0F) {
        size += 1 + 4;
      }
      if (BicepLeft != 0F) {
        size += 1 + 4;
      }
      if (BicepRight != 0F) {
        size += 1 + 4;
      }
      if (ShoulderRollLeft != 0F) {
        size += 1 + 4;
      }
      if (ShoulderRollRight != 0F) {
        size += 1 + 4;
      }
      if (ForearmRollLeft != 0F) {
        size += 1 + 4;
      }
      if (ForearmRollRight != 0F) {
        size += 1 + 4;
      }
      if (WristFlexionLeft != 0F) {
        size += 1 + 4;
      }
      if (WristFlexionRight != 0F) {
        size += 1 + 4;
      }
      if (WristYawLeft != 0F) {
        size += 1 + 4;
      }
      if (WristYawRight != 0F) {
        size += 1 + 4;
      }
      if (GripperLeft != 0F) {
        size += 1 + 4;
      }
      if (GripperRight != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RobotCalling other) {
      if (other == null) {
        return;
      }
      if (other.ShoulderPitchLeft != 0F) {
        ShoulderPitchLeft = other.ShoulderPitchLeft;
      }
      if (other.ShoulderPitchRight != 0F) {
        ShoulderPitchRight = other.ShoulderPitchRight;
      }
      if (other.BicepLeft != 0F) {
        BicepLeft = other.BicepLeft;
      }
      if (other.BicepRight != 0F) {
        BicepRight = other.BicepRight;
      }
      if (other.ShoulderRollLeft != 0F) {
        ShoulderRollLeft = other.ShoulderRollLeft;
      }
      if (other.ShoulderRollRight != 0F) {
        ShoulderRollRight = other.ShoulderRollRight;
      }
      if (other.ForearmRollLeft != 0F) {
        ForearmRollLeft = other.ForearmRollLeft;
      }
      if (other.ForearmRollRight != 0F) {
        ForearmRollRight = other.ForearmRollRight;
      }
      if (other.WristFlexionLeft != 0F) {
        WristFlexionLeft = other.WristFlexionLeft;
      }
      if (other.WristFlexionRight != 0F) {
        WristFlexionRight = other.WristFlexionRight;
      }
      if (other.WristYawLeft != 0F) {
        WristYawLeft = other.WristYawLeft;
      }
      if (other.WristYawRight != 0F) {
        WristYawRight = other.WristYawRight;
      }
      if (other.GripperLeft != 0F) {
        GripperLeft = other.GripperLeft;
      }
      if (other.GripperRight != 0F) {
        GripperRight = other.GripperRight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            ShoulderPitchLeft = input.ReadFloat();
            break;
          }
          case 21: {
            ShoulderPitchRight = input.ReadFloat();
            break;
          }
          case 29: {
            BicepLeft = input.ReadFloat();
            break;
          }
          case 37: {
            BicepRight = input.ReadFloat();
            break;
          }
          case 45: {
            ShoulderRollLeft = input.ReadFloat();
            break;
          }
          case 53: {
            ShoulderRollRight = input.ReadFloat();
            break;
          }
          case 61: {
            ForearmRollLeft = input.ReadFloat();
            break;
          }
          case 69: {
            ForearmRollRight = input.ReadFloat();
            break;
          }
          case 77: {
            WristFlexionLeft = input.ReadFloat();
            break;
          }
          case 85: {
            WristFlexionRight = input.ReadFloat();
            break;
          }
          case 93: {
            WristYawLeft = input.ReadFloat();
            break;
          }
          case 101: {
            WristYawRight = input.ReadFloat();
            break;
          }
          case 109: {
            GripperLeft = input.ReadFloat();
            break;
          }
          case 117: {
            GripperRight = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            ShoulderPitchLeft = input.ReadFloat();
            break;
          }
          case 21: {
            ShoulderPitchRight = input.ReadFloat();
            break;
          }
          case 29: {
            BicepLeft = input.ReadFloat();
            break;
          }
          case 37: {
            BicepRight = input.ReadFloat();
            break;
          }
          case 45: {
            ShoulderRollLeft = input.ReadFloat();
            break;
          }
          case 53: {
            ShoulderRollRight = input.ReadFloat();
            break;
          }
          case 61: {
            ForearmRollLeft = input.ReadFloat();
            break;
          }
          case 69: {
            ForearmRollRight = input.ReadFloat();
            break;
          }
          case 77: {
            WristFlexionLeft = input.ReadFloat();
            break;
          }
          case 85: {
            WristFlexionRight = input.ReadFloat();
            break;
          }
          case 93: {
            WristYawLeft = input.ReadFloat();
            break;
          }
          case 101: {
            WristYawRight = input.ReadFloat();
            break;
          }
          case 109: {
            GripperLeft = input.ReadFloat();
            break;
          }
          case 117: {
            GripperRight = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RobotCall.RobotCallReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      transmitted_ = other.transmitted_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "transmitted" field.</summary>
    public const int TransmittedFieldNumber = 1;
    private bool transmitted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Transmitted {
      get { return transmitted_; }
      set {
        transmitted_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Transmitted != other.Transmitted) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Transmitted != false) hash ^= Transmitted.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Transmitted != false) {
        output.WriteRawTag(8);
        output.WriteBool(Transmitted);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Transmitted != false) {
        output.WriteRawTag(8);
        output.WriteBool(Transmitted);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Transmitted != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Transmitted != false) {
        Transmitted = other.Transmitted;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Transmitted = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Transmitted = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code